//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_dust2_city.html
gfx/env/zp_trains2bk.tga
gfx/env/zp_trains2dn.tga
gfx/env/zp_trains2ft.tga
gfx/env/zp_trains2lf.tga
gfx/env/zp_trains2rt.tga
gfx/env/zp_trains2up.tga
models/zm_dust2st/ze_palmtree.mdl
models/zm_dust2st/bush_03.mdl
models/zm_dust2st/tree_05a.mdl
models/zm_dust2st/mack2.mdl
models/zm_dust2st/viper.mdl
sound/zm_dust2st/outside_wind.wav
sound/zm_dust2st/fh_03.wav
sound/zm_dust2st/water_01.wav
sound/zm_dust2st/music_4.wav
maps/zm_dust2_city.bsp
